name: Health check

on:
  schedule:
    - cron: "5 * * * *"

jobs:
  health_check:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@b716ccb #v4
        with:
          url: https://full-stack-open-pokedex-vecg.onrender.com/health